### ISSUE TITLE
Something change on IMDB site, so chrome extension stop working

### ISSUE THREAD

**Issue by Funkadelik** [shadyabhi/IMDb-Ratings-Viewer#12]
And imdb add ratings for few movies near posters at the top of page https://ibb.co/nrb1rtn

**Comment by shadyabhi** [comment]
Hey @Funkadelik , thanks for reporting. I really appreciate reports like these. It is indeed a catch-up game with IMDB website. Looks like they've changed the UI. 

I'll fix it tomorrow on Friday post lunch hours or over the weekend. Thanks!
