### ISSUE TITLE
Native ratings support

### ISSUE THREAD

**Issue by dnicolson** [shadyabhi/IMDb-Ratings-Viewer#15]
IMDb now adds ratings that look extremely similar to the latest design from this extension (except all stars are yellow).

Is there any functionality that is still needed from this extension?

**Comment by shadyabhi** [comment]
@dnicolson 11 years later, looks like its time to decommission this extension. Thank you for the report. 

I'm unsure if there's a use-case but In terms of next steps, I was wondering if we can add some visual cues in what IMDB already provides:- 

* If rating < x, turn star to `red`. x is configurable in settings. 
* Filter movie list that has ratings < x. 

However, all these features are somewhat diverting from the main focus of this extension which was simply adding the ratings. 

I'll take down and archive the repository unless someone has any interesting ideas.

**Comment by shadyabhi** [comment]
There's this feature that can be implemented too: https://github.com/shadyabhi/IMDb-Ratings-Viewer/issues/8 , not as useful though.

**Comment by dnicolson** [comment]
I did like the red stars, but hey, it's better than playing catchup with the design changes.

Thanks for merging all the PRs!

**Comment by shadyabhi** [comment]
>it's better than playing catchup with the design changes.

Yup, thanks a lot for all the contributions.
